// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbs02mSgUma8B_72mkE2m38r9I3O6D_nE',
    appId: '1:748910689840:web:994c75466fd94c9af537f5',
    messagingSenderId: '748910689840',
    projectId: 'subwatch-e870b',
    authDomain: 'subwatch-e870b.firebaseapp.com',
    databaseURL:
        'https://subwatch-e870b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'subwatch-e870b.appspot.com',
    measurementId: 'G-V0R1S8Z2Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtOtzjqIlf-nq3fc6gcfO1LdtEinRp4g',
    appId: '1:748910689840:android:0773d062c26a6bbbf537f5',
    messagingSenderId: '748910689840',
    projectId: 'subwatch-e870b',
    databaseURL:
        'https://subwatch-e870b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'subwatch-e870b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXPfnWVx-SEHdeOjQUvdBGSj36MPNVn2g',
    appId: '1:748910689840:ios:eea8fa2b6f1a6c9cf537f5',
    messagingSenderId: '748910689840',
    projectId: 'subwatch-e870b',
    databaseURL:
        'https://subwatch-e870b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'subwatch-e870b.appspot.com',
    androidClientId:
        '748910689840-qvbcg4f0hopl12qkhbuglhqh2jk634tk.apps.googleusercontent.com',
    iosClientId:
        '748910689840-5b24n3i9n0vi3qcr041va5l2p49a7hbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.subWatchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXPfnWVx-SEHdeOjQUvdBGSj36MPNVn2g',
    appId: '1:748910689840:ios:5c7da1fc8e5b5130f537f5',
    messagingSenderId: '748910689840',
    projectId: 'subwatch-e870b',
    databaseURL:
        'https://subwatch-e870b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'subwatch-e870b.appspot.com',
    androidClientId:
        '748910689840-qvbcg4f0hopl12qkhbuglhqh2jk634tk.apps.googleusercontent.com',
    iosClientId:
        '748910689840-mnovkfgve552tr96lfs97bibvjf7vtg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.subWatchFlutter.RunnerTests',
  );
}
